name = "MadIPM"
uuid = "4406d55e-1099-4ca6-ac6a-6cf051b10024"
version = "0.1.2"
authors = ["Fran√ßois Pacaud <francoispacaud8@gmail.com>", "Alexis Montoison <amontoison@anl.gov>"]

[deps]
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[sources]
MadNLP = {path = "../MadNLP.jl"}

[extensions]
MadIPMCUDAExt = ["CUDA", "CUDSS", "KernelAbstractions", "MadNLPGPU"]
MadIPMMathOptInterfaceExt = "MathOptInterface"

[compat]
CUDA = "5.4.0"
CUDSS = "0.6"
KernelAbstractions = "0.9"
LDLFactorizations = "0.10.1"
LinearAlgebra = "1.10"
MadNLP = "0.8.12"
MadNLPGPU = "0.7.15"
MadNLPTests = "0.5.3"
MathOptInterface = "1.42"
NLPModels = "0.21.5"
Printf = "1.10"
QuadraticModels = "0.9.14"
SparseArrays = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
MadNLPTests = "b52a2a03-04ab-4a5f-9698-6a2deff93217"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CUDA", "CUDSS", "KernelAbstractions", "MadNLPTests", "MadNLPGPU", "MathOptInterface", "Test"]
